/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP2
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <ESSwitch.h>
#include <ESSwitch_aliases.h>
#include <PWM.h>
#include <ShutdownSwich.h>
#include <ShutdownSwich_aliases.h>
#include <I2CVuggesystem.h>
#include <I2CVuggesystem_PINS.h>
#include <I2CVuggesystem_PVT.h>
#include <I2CVuggesystem_EZI2C.h>
#include <I2CVuggesystem_EZI2C_PVT.h>
#include <I2CVuggesystem_BOOT.h>
#include <Endstop_isr.h>
#include <Clock_1.h>
#include <activityDebug.h>
#include <activityDebug_aliases.h>
#include <PWM_A.h>
#include <PWM_A_aliases.h>
#include <PWM_B.h>
#include <PWM_B_aliases.h>
#include <t_clk.h>
#include <loopTimer.h>
#include <loop_isr.h>
#include <sensorI2C.h>
#include <sensorI2C_I2C.h>
#include <sensorI2C_PINS.h>
#include <sensorI2C_I2C_PVT.h>
#include <sensorI2C_PVT.h>
#include <sensorI2C_BOOT.h>
#include <debugOut.h>
#include <I2CVuggesystem_SCBCLK.h>
#include <I2CVuggesystem_sda.h>
#include <I2CVuggesystem_sda_aliases.h>
#include <I2CVuggesystem_scl.h>
#include <I2CVuggesystem_scl_aliases.h>
#include <I2CVuggesystem_SCB_IRQ.h>
#include <sensorI2C_SCBCLK.h>
#include <sensorI2C_sda.h>
#include <sensorI2C_sda_aliases.h>
#include <sensorI2C_scl.h>
#include <sensorI2C_scl_aliases.h>
#include <sensorI2C_SCB_IRQ.h>
#include <debugOut_IntClock.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

