/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP2
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <I2C.h>
#include <I2C_I2C.h>
#include <I2C_PINS.h>
#include <I2C_I2C_PVT.h>
#include <I2C_PVT.h>
#include <I2C_BOOT.h>
#include <UART.h>
#include <UART_SPI_UART.h>
#include <UART_PINS.h>
#include <UART_SPI_UART_PVT.h>
#include <UART_PVT.h>
#include <UART_BOOT.h>
#include <Clock_1.h>
#include <PWM_1.h>
#include <GYRO_DR.h>
#include <GYRO_DR_aliases.h>
#include <GYRO_DR_INT.h>
#include <Pin_1.h>
#include <Pin_1_aliases.h>
#include <I2C_SCBCLK.h>
#include <I2C_sda.h>
#include <I2C_sda_aliases.h>
#include <I2C_scl.h>
#include <I2C_scl_aliases.h>
#include <I2C_SCB_IRQ.h>
#include <UART_SCBCLK.h>
#include <UART_tx.h>
#include <UART_tx_aliases.h>
#include <UART_rx.h>
#include <UART_rx_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

