# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Felix\Git repositories\E4PRJ4\Implementering\Vuggesystem\Vinkelsensor.cydsn\Vinkelsensor.cyprj
# Date: Thu, 23 Apr 2015 11:48:26 GMT
#set_units -time ns
create_clock -name {I2C_SCBCLK(FFB)} -period 625 -waveform {0 312.5} [list [get_pins {ClockBlock/ff_div_2}]]
create_clock -name {UART_SCBCLK(FFB)} -period 729.16666666666663 -waveform {0 364.583333333333} [list [get_pins {ClockBlock/ff_div_3}]]
create_clock -name {CyHFCLK} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/hfclk}]]
create_generated_clock -name {I2C_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 31 61} [list]
create_generated_clock -name {UART_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 35 71} [list]
create_clock -name {CyIMO} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CySYSCLK} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/sysclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyRouted1} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/dsi_in_0}]]


# Component constraints for C:\Users\Felix\Git repositories\E4PRJ4\Implementering\Vuggesystem\Vinkelsensor.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Felix\Git repositories\E4PRJ4\Implementering\Vuggesystem\Vinkelsensor.cydsn\Vinkelsensor.cyprj
# Date: Thu, 23 Apr 2015 11:48:13 GMT
